### PR TITLE
Newcows

### PR DESCRIPTION
**Pull request by jasonkhanlar**
Per my comment at https://github.com/piuccio/cowsay/issues/38#issuecomment-432561011
And after my previous pull request minutes ago https://github.com/piuccio/cowsay/pull/39
here are a bunch of additional *.cow files pulled from the other repos listed.

### CODE REVIEW

**Comment by piuccio** [comment]
wow, I don't usually accept new cows but this is such an amazing PR. Would you mind just adding these new files on `browsers.js`. There's a list there that is needed for people using `cowsay` in the browser

**Comment by jasonkhanlar** [comment]
```
for i in *.cow;do
    ucname=$(echo $i|sed "s|[-.]|_|g"|sed "s|^\(.*\)_cow$|\1|"|tr a-z A-Z);
    echo "export { default as $ucname } from '.cows/$i';";
done
```

**Comment by piuccio** [comment]
can you please remove `chop($eyes)` from the files and the `EOC` at the bottom of new cows? After that it's ready to be merged

**Comment by jasonkhanlar** [comment]
> can you please remove ..... the `EOC` at the bottom of new cows?

I am not sure if that is a good idea. I notice all the existing cowfiles have `EOC` line at the end

Also lib/replacer.js:
```
function extractTheCow (cow) {
	cow = cow.replace(/\r\n?|[\n\u2028\u2029]/g, "\n").replace(/^\uFEFF/, '');
	var match = /\$the_cow\s*=\s*<<"*EOC"*;*\n([\s\S]+)\nEOC\n/.exec(cow);

	if (!match) {
		console.error("Cannot parse cow file\n", cow);
		return cow;
	} else {
		return match[1].replace(/\\{2}/g, "\\").replace(/\\@/g, "@").replace(/\\\$/g, "$");
	}
}
```
The match variable will evaluate to false without the `EOC` line at end?

**Comment by piuccio** [comment]
Oh I forgot the EOC was part of the regexp, I'll review your changes tomorrow

**Comment by jasonkhanlar** [comment]
bump

**Comment by piuccio** [comment]
oh totally forgot, I'll have a look soon

**Comment by piuccio** [comment]
you know what I'm thinking? Maybe we should allow cows from node modules, kinda like plugins.
You'll be able to create your own repo, change it as you like and cowsay will use your cows as well as the default ones.

What do you think? I can do some changes in the code to allow that

**Pull request merged**
