### PR TITLE
Support CJK characters

### PR DESCRIPTION
**Pull request by xavieryao**
Calculate string width correctly for strings with CJK characters.

### CODE REVIEW

**Comment by xavieryao** [comment]
Seems that `const` cannot be used. :)

**Comment by piuccio** [comment]
Hi @xavieryao thanks for the PR. Yeah this module still supports node 0.12 which doesn't have `const`

I know that 0.12 is EOL but I don't have time to update.
In the meantime you can fix the version of `string-width` to `1.0.2` that should work

**Comment by xavieryao** [comment]
I believe that now you can merge it.

**Comment by piuccio** [comment]
@xavieryao sorry if it took too long to merge.

I've cherry picked your commits and released a new version, `1.2.1`

**Pull request closed without merging**
