### PR TITLE
Fix #13: Add option -r to select a random cow

### LINKED ISSUE #13: Random cowfile option
Can you please add an option to make cowsay select a random cowfile every time? I think it would be fun in conjunction with fortune.

### PR DESCRIPTION
**Pull request by doug2k1**
Added -r option just for CLI. I could try adding for the browsers also, if that's desirable.

### CODE REVIEW

**Comment by doug2k1** [comment]
Sure! I'll look into it tonight.

**Comment by doug2k1** [comment]
Hi, I fixed the indentation.

Still working on the browser version. I'm not sure if it's possible without braking the tree-shaking possibility, since I'll have to import all cows to randomize between them.

**Comment by piuccio** [comment]
That's true, let's leave it for now, it's quite easy to implement random
cows client side

**Comment by piuccio** [comment]
Sorry I completely forgot about this, released in `1.3.0`

**Pull request merged**
