### PR TITLE
Add doge.cow

### PR DESCRIPTION
**Pull request by xshen4**
Attempt at doge, feedback welcome 

Basically used this as inspiration via google images 

http://s.mlkshk-cdn.com/r/VD6Y

screen shot 2015-11-04 at 9 53 56 pm

### CODE REVIEW

**Comment by piuccio** [comment]
hi thanks for the PR!

is it necessary to change the permissions of `cli.js`? I see that you added execution.
Was it not working before?

**Comment by xshen4** [comment]
Hi! Ah I meant to remove that from my commit.  The way I was able to build a local version of this from the repo is:

```
npm link
```

But due to permissioning issues I wasn't able to execute cowsay.  I can get more details on it, but I attributed it to a local issue rather than code. I'll update this PR since it's not really related to remove the cli.js commit!

**Comment by xshen4** [comment]
@piuccio looks like I cloned my repo as root, and that's why I was getting those permission issues. My bad :) Fixed and removed cli.js from the commit!

**Comment by piuccio** [comment]
wonderful thanks

**Comment by piuccio** [comment]
I've published this in `1.1.2`

**Pull request merged**
